#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    if [ -f $2/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $2/.tmux-sessionizer" C-m
    elif [ -f $HOME/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $HOME/.tmux-sessionizer" C-m
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find  ~/Desktop/Sites/ ~/.config/nvim/  -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

create_windows() {
    local session=$1
    local location=$2

    # Rename the default first window to "Vim" and set its directory
    tmux rename-window -t "$session:1" "Vim"
    tmux send-keys -t "$session:1" "cd \"$location\" && vim ." C-m

    # Create a second window named "Docker" and set its directory
    tmux new-window -t "$session:2" -n "Docker" -c "$location"
    tmux send-keys -t "$session:2" "cd \"$location\" && docker ps" C-m

    # Create a third window named "Shell" and set its directory
    tmux new-window -t "$session:3" -n "Shell" -c "$location"
    tmux send-keys -t "$session:3" "cd \"$location\" && zsh" C-m

    # Ensure the "Vim" window is selected by default
    tmux select-window -t "$session:1"
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -d -s $selected_name -c $selected
    create_windows "$selected_name" "$selected"
    hydrate $selected_name $selected
    tmux attach-session -t $selected_name
    exit 0
fi

if ! has_session $selected_name; then
    tmux new-session -d -s $selected_name -c $selected
    create_windows "$selected_name" "$selected"
    hydrate $selected_name $selected
fi

switch_to $selected_name

